sudo: required

services:
  - docker

before_install:
  - docker pull moussavdb/build-java-native

script:
  - docker run -v $PWD:/src -w /src moussavdb/build-java-native mvn -V -s settings.xml clean install -Pbuild,native-sonar -Dsonar.cfamily.build-wrapper-output=target/sonar-cpp
